apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "change port 80"
  name: deployment-test2
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mi-service1
  labels:
    app: backend
spec:
  selector:
    app: backend
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
