apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    name: prod
---
apiVersion: v1
kind: LimitRange
metadata:
  name: mem-min
  namespace: prod
spec:
  limits:
  - max:
      memory: 1Gi
      cpu: 1
    min:
      memory: 500Mi
      cpu: 100m
    type: Container
---
apiVersion: v1
kind: Pod
metadata:
  name: podtest
  namespace: prod
  labels:
    name: test
spec:
  containers:
  - name: cont1
    image: nginx:alpine
    resources:
      limits:
        memory: 750Mi 
        cpu: 0.5
      requests:
        memory: 500Mi
        cpu: 0.3


