apiVersion: v1
kind: Pod
metadata:
  name: envar-demo
  labels:
    purpose: demonstrate-envars
spec:
  containers:
  - name: envar-demo-container
    image: nginx:alpine
    env:
    - name: VAR1
      value: "primer valor de preba"
    - name: VAR2
      value: "test2"
    - name: VAR3
      value: "test3"

