apiVersion: v1
kind: Pod
metadata:  
  name: myapp-pod1
  labels:
    app: front
    env: dev
spec:
  containers:
  - name: container1
    image: nginx:alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod2
  labels:
    app: backend
    env: dev
spec:
  containers:
  - name: container1
    image: nginx:alpine
