apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: default
type: Opaque
data:
  insegure_username: dXNlcm5hbWUK
  insegure_password: cGFzc3dvcmQK
  # Example:
  # password: {{ .Values.password | b64enc }}
---

