# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: mysecret2
  namespace: default
type: Opaque
stringData:
  username: usertest
  password: passowordtest
  # Example:
  # password: {{ .Values.password | b64enc }}
---

