# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: mysecret3
  namespace: default
type: Opaque
stringData:
  username: $USER
  password: $PASSWORD
---

